In [48]:
import re
import requests
from bs4 import BeautifulSoup

import pandas as pd

## Function to get entire listing

In [49]:
def get_listings(result):
    
    listings = []
    
    for d in result.findAll(class_ = "placard-details module"):

        listings.append(d)

    return listings

## Combining all parameters of each property

In [59]:
58.176.46.248

proxies = {
    'http':'http://192.25.162.203'
    }
#, 'http://45.32.23.218', ,'http://168.63.20.19','http://168.63.24.174', 'http': 'http://142.0.128.218'
url = 'http://www.loopnet.com/for-lease/new-york-ny/retail/'

#results = []

r = requests.get(url, proxies=proxies)

page = r.content
soup = BeautifulSoup(page, 'lxml')

results = (get_listings(soup))

In [60]:
results

[<div class="placard-details module">\n<h5 class="listing-address">\n<a class="column-09" href="http://www.loopnet.com/Listing/19621797/134-West-37th-Street-New-York-NY/" ng-click="RedirectToProfile('http://www.loopnet.com/Listing/19621797/134-West-37th-Street-New-York-NY/'); $event.stopPropagation();" title="134 West 37th Street">\n<address itemprop="address" itemscope="" itemtype="http://schema.org/PostalAddress">\n<span class="street-address" itemprop="streetAddress" title="134 West 37th Street">134 West 37th Street</span>\n<span itemprop="addressLocality" title="New York, NY">New York</span>,\r\n    <span itemprop="addressState" title="NY, NY">NY</span>\n<span itemprop="postalCode" title="10018">10018</span>\n</address>\n</a>\n<span class="listing-price column-04">$45-$79.20 SF/Year</span>\n</h5>\n<ul>\n<li>\n<span>Office Bldg</span>\n</li>\n<li>\n<i>2,500 - 10,000</i>\n<span>SF Available</span>\n</li>\n<li>\n<i>2</i>\n<span>Spaces</span>\n</li>\n<li>\n<i>120,000</i>\n<span>SF Bldg</span>\n</li>\n</ul>\n<p class="property-description">Extremely desirable office space in the heart of the fashion district.  Ground Floor Retail also available.</p>\n</div>,
 <div class="placard-details module">\n<h5 class="listing-address">\n<a class="column-09" href="http://www.loopnet.com/Listing/19852777/517-Columbus-Avenue-New-York-NY/" ng-click="RedirectToProfile('http://www.loopnet.com/Listing/19852777/517-Columbus-Avenue-New-York-NY/'); $event.stopPropagation();" title="517 Columbus Avenue">\n<address itemprop="address" itemscope="" itemtype="http://schema.org/PostalAddress">\n<span class="street-address" itemprop="streetAddress" title="517 Columbus Avenue">517 Columbus Avenue</span>\n<span itemprop="addressLocality" title="New York, NY">New York</span>,\r\n    <span itemprop="addressState" title="NY, NY">NY</span>\n<span itemprop="postalCode" title="10024">10024</span>\n</address>\n</a>\n<span class="listing-price column-04">$204.60 SF/Year</span>\n</h5>\n<ul>\n<li>\n<span>Restaurant</span>\n</li>\n<li>\n<i>2,346</i>\n<span>SF Available</span>\n</li>\n<li>\n<i>1</i>\n<span>Space</span>\n</li>\n<li>\n<i>2,345</i>\n<span>SF Bldg</span>\n</li>\n</ul>\n<p class="property-description">This is the former Jackson Hole space has not being on the market for over 40 years, With high ceilings, French doors to a sidewalk cafe and...</p>\n</div>,
 <div class="placard-details module">\n<h5 class="listing-address">\n<a class="column-10" href="http://www.loopnet.com/Listing/19584842/76-Wooster-St-New-York-NY/" ng-click="RedirectToProfile('http://www.loopnet.com/Listing/19584842/76-Wooster-St-New-York-NY/'); $event.stopPropagation();" title="76 Wooster St">\n<address itemprop="address" itemscope="" itemtype="http://schema.org/PostalAddress">\n<span class="street-address" itemprop="streetAddress" title="76 Wooster St">76 Wooster St</span>\n<span itemprop="addressLocality" title="New York, NY">New York</span>,\r\n    <span itemprop="addressState" title="NY, NY">NY</span>\n<span itemprop="postalCode" title="10012">10012</span>\n</address>\n</a>\n<span class="listing-price">$80-$84 SF/Year</span>\n</h5>\n<p class="property-name" modelprop="name">SoHo Retail and Office Spaces</p>\n<ul>\n<li>\n<span>Street Retail</span>\n</li>\n<li>\n<i>3,000 - 5,000</i>\n<span>SF Available</span>\n</li>\n<li>\n<i>2</i>\n<span>Spaces</span>\n</li>\n<li>\n<i>10,000</i>\n<span>SF Bldg</span>\n</li>\n</ul>\n</div>,
 <div class="placard-details module">\n<h5 class="listing-address">\n<a class="column-10" href="http://www.loopnet.com/Listing/19632482/117-East-15th-Street-New-York-NY/" ng-click="RedirectToProfile('http://www.loopnet.com/Listing/19632482/117-East-15th-Street-New-York-NY/'); $event.stopPropagation();" title="117 East 15th Street">\n<address itemprop="address" itemscope="" itemtype="http://schema.org/PostalAddress">\n<span class="street-address" itemprop="streetAddress" title="117 East 15th Street">117 East 15th Street</span>\n<span itemprop="addressLocality" title="New York, NY">New York</span>,\r\n    <span itemprop="addressState" title="NY, NY">NY</span>\n<span itemprop="postalCode" title="10003">10003</span>\n</address>\n</a>\n<span class="listing-price">$110.67-$120 SF/Year</span>\n</h5>\n<p class="property-name" modelprop="name">Prime Union Square Multi-Level Brownstone Retail</p>\n<ul>\n<li>\n<span>Restaurant</span>\n</li>\n<li>\n<i>3,300 - 6,600</i>\n<span>SF Available</span>\n</li>\n<li>\n<i>3</i>\n<span>Spaces</span>\n</li>\n<li>\n<i>6,600</i>\n<span>SF Bldg</span>\n</li>\n</ul>\n</div>,
 <div class="placard-details module">\n<h5 class="listing-address">\n<a class="column-10" href="http://www.loopnet.com/Listing/19872387/250-Hudson-St-New-York-NY/" ng-click="RedirectToProfile('http://www.loopnet.com/Listing/19872387/250-Hudson-St-New-York-NY/'); $event.stopPropagation();" title="250 Hudson St">\n<address itemprop="address" itemscope="" itemtype="http://schema.org/PostalAddress">\n<span class="street-address" itemprop="streetAddress" title="250 Hudson St">250 Hudson St</span>\n<span itemprop="addressLocality" title="New York, NY">New York</span>,\r\n    <span itemprop="addressState" title="NY, NY">NY</span>\n<span itemprop="postalCode" title="10013">10013</span>\n</address>\n</a>\n<span class="listing-price">$75-$90 SF/Year</span>\n</h5>\n<ul>\n<li>\n<span>Office Bldg</span>\n</li>\n<li>\n<i>3,100 - 15,832</i>\n<span>SF Available</span>\n</li>\n<li>\n<i>3</i>\n<span>Spaces</span>\n</li>\n<li>\n<i>394,424</i>\n<span>SF Bldg</span>\n</li>\n</ul>\n</div>,
 <div class="placard-details module">\n<h5 class="listing-address">\n<a class="column-10" href="http://www.loopnet.com/Listing/19872550/485-Madison-Ave-New-York-NY/" ng-click="RedirectToProfile('http://www.loopnet.com/Listing/19872550/485-Madison-Ave-New-York-NY/'); $event.stopPropagation();" title="485 Madison Ave">\n<address itemprop="address" itemscope="" itemtype="http://schema.org/PostalAddress">\n<span class="street-address" itemprop="streetAddress" title="485 Madison Ave">485 Madison Ave</span>\n<span itemprop="addressLocality" title="New York, NY">New York</span>,\r\n    <span itemprop="addressState" title="NY, NY">NY</span>\n<span itemprop="postalCode" title="10022">10022</span>\n</address>\n</a>\n<span class="listing-price">$54-$550 SF/Year</span>\n</h5>\n<ul>\n<li>\n<span>Office Bldg</span>\n</li>\n<li>\n<i>654 - 31,472</i>\n<span>SF Available</span>\n</li>\n<li>\n<i>3</i>\n<span>Spaces</span>\n</li>\n<li>\n<i>302,000</i>\n<span>SF Bldg</span>\n</li>\n</ul>\n</div>,
 <div class="placard-details module">\n<h5 class="listing-address">\n<a class="column-10" href="http://www.loopnet.com/Listing/18803035/315-Madison-Ave-New-York-NY/" ng-click="RedirectToProfile('http://www.loopnet.com/Listing/18803035/315-Madison-Ave-New-York-NY/'); $event.stopPropagation();" title="315 Madison Ave">\n<address itemprop="address" itemscope="" itemtype="http://schema.org/PostalAddress">\n<span class="street-address" itemprop="streetAddress" title="315 Madison Ave">315 Madison Ave</span>\n<span itemprop="addressLocality" title="New York, NY">New York</span>,\r\n    <span itemprop="addressState" title="NY, NY">NY</span>\n<span itemprop="postalCode" title="10017">10017</span>\n</address>\n</a>\n<span class="listing-price">$60-$355 SF/Year</span>\n</h5>\n<ul>\n<li>\n<span>Office Bldg</span>\n</li>\n<li>\n<i>1,802 - 3,894</i>\n<span>SF Available</span>\n</li>\n<li>\n<i>4</i>\n<span>Spaces</span>\n</li>\n<li>\n<i>148,370</i>\n<span>SF Bldg</span>\n</li>\n</ul>\n</div>,
 <div class="placard-details module">\n<h5 class="listing-address">\n<a class="column-10" href="http://www.loopnet.com/Listing/19872441/315-Hudson-St-New-York-NY/" ng-click="RedirectToProfile('http://www.loopnet.com/Listing/19872441/315-Hudson-St-New-York-NY/'); $event.stopPropagation();" title="315 Hudson St">\n<address itemprop="address" itemscope="" itemtype="http://schema.org/PostalAddress">\n<span class="street-address" itemprop="streetAddress" title="315 Hudson St">315 Hudson St</span>\n<span itemprop="addressLocality" title="New York, NY">New York</span>,\r\n    <span itemprop="addressState" title="NY, NY">NY</span>\n<span itemprop="postalCode" title="10013">10013</span>\n</address>\n</a>\n<span class="listing-price">$100-$175 SF/Year</span>\n</h5>\n<ul>\n<li>\n<span>Office Bldg</span>\n</li>\n<li>\n<i>3,922 - 5,881</i>\n<span>SF Available</span>\n</li>\n<li>\n<i>5</i>\n<span>Spaces</span>\n</li>\n<li>\n<i>485,577</i>\n<span>SF Bldg</span>\n</li>\n</ul>\n</div>,
 <div class="placard-details module">\n<h5 class="listing-address">\n<a class="column-10" href="http://www.loopnet.com/Listing/20002133/261-Fifth-Ave-New-York-NY/" ng-click="RedirectToProfile('http://www.loopnet.com/Listing/20002133/261-Fifth-Ave-New-York-NY/'); $event.stopPropagation();" title="261 Fifth Ave">\n<address itemprop="address" itemscope="" itemtype="http://schema.org/PostalAddress">\n<span class="street-address" itemprop="streetAddress" title="261 Fifth Ave">261 Fifth Ave</span>\n<span itemprop="addressLocality" title="New York, NY">New York</span>,\r\n    <span itemprop="addressState" title="NY, NY">NY</span>\n<span itemprop="postalCode" title="10001">10001</span>\n</address>\n</a>\n<span class="listing-price">Negotiable<br/>Rate</span>\n</h5>\n<p class="property-name" modelprop="name">261 5th Avenue</p>\n<ul>\n<li>\n<span>Office Bldg</span>\n</li>\n<li>\n<i>1,590 - 21,457</i>\n<span>SF Available</span>\n</li>\n<li>\n<i>3</i>\n<span>Spaces</span>\n</li>\n<li>\n<i>444,716</i>\n<span>SF Bldg</span>\n</li>\n</ul>\n</div>,
 <div class="placard-details module">\n<h5 class="listing-address">\n<a class="column-10" href="http://www.loopnet.com/Listing/19271844/100-Broad-St-New-York-NY/" ng-click="RedirectToProfile('http://www.loopnet.com/Listing/19271844/100-Broad-St-New-York-NY/'); $event.stopPropagation();" title="100 Broad St">\n<address itemprop="address" itemscope="" itemtype="http://schema.org/PostalAddress">\n<span class="street-address" itemprop="streetAddress" title="100 Broad St">100 Broad St</span>\n<span itemprop="addressLocality" title="New York, NY">New York</span>,\r\n    <span itemprop="addressState" title="NY, NY">NY</span>\n<span itemprop="postalCode" title="10004">10004</span>\n</address>\n</a>\n<span class="listing-price">$94 SF/Year</span>\n</h5>\n<p class="property-name" modelprop="name">Prime Retail/Office+ Rooftop in Financial District</p>\n<ul>\n<li>\n<span>Restaurant</span>\n</li>\n<li>\n<i>8,000</i>\n<span>SF Available</span>\n</li>\n<li>\n<i>1</i>\n<span>Space</span>\n</li>\n<li>\n<i>10,000</i>\n<span>SF Bldg</span>\n</li>\n</ul>\n</div>,
 <div class="placard-details module">\n<h5 class="listing-address">\n<a class="column-10" href="http://www.loopnet.com/Listing/19963876/143-Orchard-St-New-York-NY/" ng-click="RedirectToProfile('http://www.loopnet.com/Listing/19963876/143-Orchard-St-New-York-NY/'); $event.stopPropagation();" title="143 Orchard St">\n<address itemprop="address" itemscope="" itemtype="http://schema.org/PostalAddress">\n<span class="street-address" itemprop="streetAddress" title="143 Orchard St">143 Orchard St</span>\n<span itemprop="addressLocality" title="New York, NY">New York</span>,\r\n    <span itemprop="addressState" title="NY, NY">NY</span>\n<span itemprop="postalCode" title="10002">10002</span>\n</address>\n</a>\n<span class="listing-price">$180 SF/Year</span>\n</h5>\n<ul>\n<li>\n<span>Other Retail</span>\n</li>\n<li>\n<i>800</i>\n<span>SF Available</span>\n</li>\n<li>\n<i>1</i>\n<span>Space</span>\n</li>\n<li>\n<i>6,472</i>\n<span>SF Bldg</span>\n</li>\n</ul>\n</div>,
 <div class="placard-details module">\n<h5 class="listing-address">\n<a class="column-10 column-medium-12 column-small-12 " href="http://www.loopnet.com/Listing/18922237/142-144-west-26-street-New-York-NY/" ng-click="RedirectToProfile('http://www.loopnet.com/Listing/18922237/142-144-west-26-street-New-York-NY/'); $event.stopPropagation();" title="142-144 west 26 street">\n<address itemprop="address" itemscope="" itemtype="http://schema.org/PostalAddress">\n<span class="street-address" itemprop="streetAddress" title="142-144 west 26 street">142-144 west 26 street</span>\n<span itemprop="addressLocality" title="New York, NY">New York</span>,\r\n    <span itemprop="addressState" title="NY, NY">NY</span>\n<span itemprop="postalCode" title="10001">10001</span>\n</address>\n</a>\n<span class="listing-price column-04 column-medium-12 column-small-12 ">$85 SF/Year</span>\n</h5>\n<p class="property-name" modelprop="name">High End Installation Showroom</p>\n<ul>\n<li>\n<span>Other Retail</span>\n</li>\n<li>\n<i>4,000</i>\n<span>SF Available</span>\n</li>\n<li>\n<i>1</i>\n<span>Space</span>\n</li>\n<li>\n<i>53,054</i>\n<span>SF Bldg</span>\n</li>\n</ul>\n</div>,
 <div class="placard-details module">\n<h5 class="listing-address">\n<a class="column-10 column-medium-12 column-small-12 " href="http://www.loopnet.com/Listing/19814141/382-Lafayette-Street-New-York-NY/" ng-click="RedirectToProfile('http://www.loopnet.com/Listing/19814141/382-Lafayette-Street-New-York-NY/'); $event.stopPropagation();" title="382 Lafayette Street">\n<address itemprop="address" itemscope="" itemtype="http://schema.org/PostalAddress">\n<span class="street-address" itemprop="streetAddress" title="382 Lafayette Street">382 Lafayette Street</span>\n<span itemprop="addressLocality" title="New York, NY">New York</span>,\r\n    <span itemprop="addressState" title="NY, NY">NY</span>\n<span itemprop="postalCode" title="10003">10003</span>\n</address>\n</a>\n<span class="listing-price column-04 column-medium-12 column-small-12 ">$218.18 SF/Year</span>\n</h5>\n<p class="property-name" modelprop="name"></p>\n<ul>\n<li>\n<span>Street Retail</span>\n</li>\n<li>\n<i>2,200</i>\n<span>SF Available</span>\n</li>\n<li>\n<i>1</i>\n<span>Space</span>\n</li>\n<li>\n<i>13,000</i>\n<span>SF Bldg</span>\n</li>\n</ul>\n</div>,
 <div class="placard-details module">\n<h5 class="listing-address">\n<a class="column-10 column-medium-12 column-small-12 " href="http://www.loopnet.com/Listing/19857624/155-West-18th-Street-New-York-NY/" ng-click="RedirectToProfile('http://www.loopnet.com/Listing/19857624/155-West-18th-Street-New-York-NY/'); $event.stopPropagation();" title="155 West 18th Street">\n<address itemprop="address" itemscope="" itemtype="http://schema.org/PostalAddress">\n<span class="street-address" itemprop="streetAddress" title="155 West 18th Street">155 West 18th Street</span>\n<span itemprop="addressLocality" title="New York, NY">New York</span>,\r\n    <span itemprop="addressState" title="NY, NY">NY</span>\n<span itemprop="postalCode" title="10011">10011</span>\n</address>\n</a>\n<span class="listing-price column-04 column-medium-12 column-small-12 ">Negotiable<br/>Rate</span>\n</h5>\n<p class="property-name" modelprop="name"></p>\n<ul>\n<li>\n<span>Street Retail</span>\n</li>\n<li>\n<i>2,440 - 7,406</i>\n<span>SF Available</span>\n</li>\n<li>\n<i>3</i>\n<span>Spaces</span>\n</li>\n<li>\n<i>7,406</i>\n<span>SF Bldg</span>\n</li>\n</ul>\n</div>,
 <div class="placard-details module">\n<h5 class="listing-address">\n<a class="column-10" href="http://www.loopnet.com/Listing/20056601/155-Chambers-St-New-York-NY/" ng-click="RedirectToProfile('http://www.loopnet.com/Listing/20056601/155-Chambers-St-New-York-NY/'); $event.stopPropagation();" title="155 Chambers St">\n<address itemprop="address" itemscope="" itemtype="http://schema.org/PostalAddress">\n<span class="street-address" itemprop="streetAddress" title="155 Chambers St">155 Chambers St</span>\n<span itemprop="addressLocality" title="New York, NY">New York</span>,\r\n    <span itemprop="addressState" title="NY, NY">NY</span>\n<span itemprop="postalCode" title="10007">10007</span>\n</address>\n</a>\n<span class="listing-price column-04">$216 SF/Year</span>\n</h5>\n<p class="property-name" modelprop="name"></p>\n<ul>\n<li>\n<span>Street Retail</span>\n</li>\n<li>\n<i>750</i>\n<span>SF Available</span>\n</li>\n<li>\n<i>1</i>\n<span>Space</span>\n</li>\n<li>\n<i>8,900</i>\n<span>SF Bldg</span>\n</li>\n</ul>\n</div>,
 <div class="placard-details module">\n<h5 class="listing-address">\n<a class="column-10" href="http://www.loopnet.com/Listing/20056597/70-74-Lafayette-St-New-York-NY/" ng-click="RedirectToProfile('http://www.loopnet.com/Listing/20056597/70-74-Lafayette-St-New-York-NY/'); $event.stopPropagation();" title="70-74 Lafayette St">\n<address itemprop="address" itemscope="" itemtype="http://schema.org/PostalAddress">\n<span class="street-address" itemprop="streetAddress" title="70-74 Lafayette St">70-74 Lafayette St</span>\n<span itemprop="addressLocality" title="New York, NY">New York</span>,\r\n    <span itemprop="addressState" title="NY, NY">NY</span>\n<span itemprop="postalCode" title="11209">11209</span>\n</address>\n</a>\n<span class="listing-price column-04">$58.50 SF/Year</span>\n</h5>\n<p class="property-name" modelprop="name"></p>\n<ul>\n<li>\n<span>Street Retail</span>\n</li>\n<li>\n<i>4,000</i>\n<span>SF Available</span>\n</li>\n<li>\n<i>1</i>\n<span>Space</span>\n</li>\n<li>\n<i>16,900</i>\n<span>SF Bldg</span>\n</li>\n</ul>\n</div>,
 <div class="placard-details module">\n<h5 class="listing-address">\n<a class="column-10" href="http://www.loopnet.com/Listing/20054534/735-Ninth-Ave-New-York-NY/" ng-click="RedirectToProfile('http://www.loopnet.com/Listing/20054534/735-Ninth-Ave-New-York-NY/'); $event.stopPropagation();" title="735 Ninth Ave">\n<address itemprop="address" itemscope="" itemtype="http://schema.org/PostalAddress">\n<span class="street-address" itemprop="streetAddress" title="735 Ninth Ave">735 Ninth Ave</span>\n<span itemprop="addressLocality" title="New York, NY">New York</span>,\r\n    <span itemprop="addressState" title="NY, NY">NY</span>\n<span itemprop="postalCode" title="10019">10019</span>\n</address>\n</a>\n<span class="listing-price column-04">Negotiable<br/>Rate</span>\n</h5>\n<p class="property-name" modelprop="name">McDonald's</p>\n<ul>\n<li>\n<span>Restaurant</span>\n</li>\n<li>\n<i>2,000</i>\n<span>SF Available</span>\n</li>\n<li>\n<i>1</i>\n<span>Space</span>\n</li>\n<li>\n<i>2,700</i>\n<span>SF Bldg</span>\n</li>\n</ul>\n</div>,
 <div class="placard-details module">\n<h5 class="listing-address">\n<a class="column-10" href="http://www.loopnet.com/Listing/20051678/274-Grand-St-New-York-NY/" ng-click="RedirectToProfile('http://www.loopnet.com/Listing/20051678/274-Grand-St-New-York-NY/'); $event.stopPropagation();" title="274 Grand St">\n<address itemprop="address" itemscope="" itemtype="http://schema.org/PostalAddress">\n<span class="street-address" itemprop="streetAddress" title="274 Grand St">274 Grand St</span>\n<span itemprop="addressLocality" title="New York, NY">New York</span>,\r\n    <span itemprop="addressState" title="NY, NY">NY</span>\n<span itemprop="postalCode" title="10002">10002</span>\n</address>\n</a>\n<span class="listing-price column-04">Negotiable<br/>Rate</span>\n</h5>\n<p class="property-name" modelprop="name"></p>\n<ul>\n<li>\n<span>Street Retail</span>\n</li>\n<li>\n<i>1,514 - 3,664</i>\n<span>SF Available</span>\n</li>\n<li>\n<i>2</i>\n<span>Spaces</span>\n</li>\n<li>\n<i>5,944</i>\n<span>SF Bldg</span>\n</li>\n</ul>\n</div>,

Every listing should include a list of :

1. listing webpage
2. street address, locality, state, postalcode
3. listing price
4. listing type (office building, restaurant, etc)
5. SF available
6. No. of spaces
7. SF building
8. property description

In [186]:
def get_listing_details(listing_placard):
    
    listing = []
    
    # listing website
    try:
        listing.append(re.findall('href="(.+)" ng-', str(listing_placard))[0])
        
         
    except:
        listing.append('')
    
    # listing streetaddress
    try:
        listing.append(re.findall('streetAddress" title="(.+)"', str(listing_placard))[0])
    except:
        listing.append('')
     
    # listing address locality
    try:
        listing.append(re.findall('addressLocality" title="(.+)"', str(listing_placard))[0])
    except:
        listing.append('')
    
    # listing state
    try:
        listing.append(re.findall('addressState" title="(.+),', str(listing_placard))[0])
    except:
        listing.append('')
    
    # listing postcode
    try:
        listing.append(re.findall('postalCode" title="(\d+)"', str(listing_placard))[0])
    except:
        listing.append('')
    
    # listing price
    try:
        listing.append(re.findall('listing-price.+>(.+)<', str(listing_placard))[0])
    except:
        listing.append('')
    
    # listing type
    try:
        listing.append(re.findall('h5>\n<ul>\n<li>\n<span>(.+)<', str(listing_placard))[0])
    except:
        listing.append('')
    
    # listing square feet available
    try:
        listing.append(re.findall('>(.+)</i>\n<span>SF Available', str(listing_placard))[0])
    except:
        listing.append('')

    # listing spaces available
    try:
        listing.append(re.findall('>(.+)</i>\n<span>Spaces', str(listing_placard))[0])
    except:
        listing.append('')
    
    # listing building square feet
    try:
        listing.append(re.findall('>(.+)</i>\n<span>SF Bldg', str(listing_placard))[0])
    except:
        listing.append('')
    
    #listing property description
    try:
        listing.append(re.findall('property-description">((.|\n|\r)*)<', str(listing_placard))[0])
    except:
        listing.append('')
    
    return listing

In [62]:
page_list = []
for i in results:
    page_list.append(get_listing_details(i))

In [63]:
col = ['Web_address', 'Street_address', 'Locality', 'State', 'Postcode', 'Price', 'Property_type', 'SF_avail', 'Spaces_avail', 'Bldg_SF', 'Prop_desc']

df = pd.DataFrame(page_list, columns= col)
df

,Web_address,Street_address,Locality,State,Postcode,Price,Property_type,SF_avail,Spaces_avail,Bldg_SF,Prop_desc
0,http://www.loopnet.com/Listing/19621797/134-We...,134 West 37th Street,"New York, NY",NY,10018,$45-$79.20 SF/Year,Office Bldg,"2,500 - 10,000",2,"120,000",Extremely desirable office space in the heart ...
1,http://www.loopnet.com/Listing/19852777/517-Co...,517 Columbus Avenue,"New York, NY",NY,10024,$204.60 SF/Year,Restaurant,"2,346",,"2,345",This is the former Jackson Hole space has not ...
2,http://www.loopnet.com/Listing/19584842/76-Woo...,76 Wooster St,"New York, NY",NY,10012,$80-$84 SF/Year,,"3,000 - 5,000",2,"10,000",
3,http://www.loopnet.com/Listing/19632482/117-Ea...,117 East 15th Street,"New York, NY",NY,10003,$110.67-$120 SF/Year,,"3,300 - 6,600",3,"6,600",
4,http://www.loopnet.com/Listing/19872387/250-Hu...,250 Hudson St,"New York, NY",NY,10013,$75-$90 SF/Year,Office Bldg,"3,100 - 15,832",3,"394,424",
5,http://www.loopnet.com/Listing/19872550/485-Ma...,485 Madison Ave,"New York, NY",NY,10022,$54-$550 SF/Year,Office Bldg,"654 - 31,472",3,"302,000",
6,http://www.loopnet.com/Listing/18803035/315-Ma...,315 Madison Ave,"New York, NY",NY,10017,$60-$355 SF/Year,Office Bldg,"1,802 - 3,894",4,"148,370",
7,http://www.loopnet.com/Listing/19872441/315-Hu...,315 Hudson St,"New York, NY",NY,10013,$100-$175 SF/Year,Office Bldg,"3,922 - 5,881",5,"485,577",
8,http://www.loopnet.com/Listing/20002133/261-Fi...,261 Fifth Ave,"New York, NY",NY,10001,Rate,,"1,590 - 21,457",3,"444,716",
9,http://www.loopnet.com/Listing/19271844/100-Br...,100 Broad St,"New York, NY",NY,10004,$94 SF/Year,,"8,000",,"10,000",
10,http://www.loopnet.com/Listing/19963876/143-Or...,143 Orchard St,"New York, NY",NY,10002,$180 SF/Year,Other Retail,800,,"6,472",
11,http://www.loopnet.com/Listing/18922237/142-14...,142-144 west 26 street,"New York, NY",NY,10001,$85 SF/Year,,"4,000",,"53,054",
12,http://www.loopnet.com/Listing/19814141/382-La...,382 Lafayette Street,"New York, NY",NY,10003,$218.18 SF/Year,,"2,200",,"13,000",
13,http://www.loopnet.com/Listing/19857624/155-We...,155 West 18th Street,"New York, NY",NY,10011,Rate,,"2,440 - 7,406",3,"7,406",
14,http://www.loopnet.com/Listing/20056601/155-Ch...,155 Chambers St,"New York, NY",NY,10007,$216 SF/Year,,750,,"8,900",
15,http://www.loopnet.com/Listing/20056597/70-74-...,70-74 Lafayette St,"New York, NY",NY,11209,$58.50 SF/Year,,"4,000",,"16,900",
16,http://www.loopnet.com/Listing/20054534/735-Ni...,735 Ninth Ave,"New York, NY",NY,10019,Rate,,"2,000",,"2,700",
17,http://www.loopnet.com/Listing/20051678/274-Gr...,274 Grand St,"New York, NY",NY,10002,Rate,,"1,514 - 3,664",2,"5,944",
18,http://www.loopnet.com/Listing/20051336/580-59...,580-590 W 161st St,"New York, NY",NY,10032,Rate,,"1,850",,"46,309",
19,http://www.loopnet.com/Listing/20050911/1143-1...,1143 1ST Ave,"New York, NY",NY,10065,$187.20 SF/Year,,"1,250",,"16,250",

In [64]:
len(page_list)

20

In [189]:
url_template1 = "http://www.loopnet.com/for-lease/ny/retail/"
url_template2 = "/?view=list"

max_pages = 25

"""58.176.46.248
4.31.142.200
64.20.45.138"""

proxies = {
    'http':'http://4.31.142.200'
    }
    
for pg in range(2, max_pages+1, 1):

    url = url_template1 + str(pg) + url_template2

    r = requests.get(url, proxies=proxies)
    if str(r) == "<Response [200]>":

        page = r.content
        soup = BeautifulSoup(page, 'lxml')

        results.append(get_listings(soup))
        for i in results:
            page_list.append(get_listing_details(i))

    else:
        print "This url is not responding favorably."
        print "url =", url
        print "response =", r

In [190]:
col = ['Web_address', 'Street_address', 'Locality', 'State', \
       'Postcode', 'Price', 'Property_type', 'SF_avail', 'Spaces_avail', 'Bldg_SF', 'Prop_desc']

df = pd.DataFrame(page_list, columns= col)

In [191]:
df.shape

(1238, 11)

In [192]:
df.to_csv('listings.csv')

In [193]:
df

,Web_address,Street_address,Locality,State,Postcode,Price,Property_type,SF_avail,Spaces_avail,Bldg_SF,Prop_desc
0,http://www.loopnet.com/Listing/19621797/134-We...,134 West 37th Street,"New York, NY",NY,10018,$45-$79.20 SF/Year,Office Bldg,"2,500 - 10,000",2,"120,000",Extremely desirable office space in the heart ...
1,http://www.loopnet.com/Listing/19852777/517-Co...,517 Columbus Avenue,"New York, NY",NY,10024,$204.60 SF/Year,Restaurant,"2,346",,"2,345",This is the former Jackson Hole space has not ...
2,http://www.loopnet.com/Listing/19584842/76-Woo...,76 Wooster St,"New York, NY",NY,10012,$80-$84 SF/Year,,"3,000 - 5,000",2,"10,000",
3,http://www.loopnet.com/Listing/19632482/117-Ea...,117 East 15th Street,"New York, NY",NY,10003,$110.67-$120 SF/Year,,"3,300 - 6,600",3,"6,600",
4,http://www.loopnet.com/Listing/19872387/250-Hu...,250 Hudson St,"New York, NY",NY,10013,$75-$90 SF/Year,Office Bldg,"3,100 - 15,832",3,"394,424",
5,http://www.loopnet.com/Listing/19872550/485-Ma...,485 Madison Ave,"New York, NY",NY,10022,$54-$550 SF/Year,Office Bldg,"654 - 31,472",3,"302,000",
6,http://www.loopnet.com/Listing/18803035/315-Ma...,315 Madison Ave,"New York, NY",NY,10017,$60-$355 SF/Year,Office Bldg,"1,802 - 3,894",4,"148,370",
7,http://www.loopnet.com/Listing/19872441/315-Hu...,315 Hudson St,"New York, NY",NY,10013,$100-$175 SF/Year,Office Bldg,"3,922 - 5,881",5,"485,577",
8,http://www.loopnet.com/Listing/20002133/261-Fi...,261 Fifth Ave,"New York, NY",NY,10001,Rate,,"1,590 - 21,457",3,"444,716",
9,http://www.loopnet.com/Listing/19271844/100-Br...,100 Broad St,"New York, NY",NY,10004,$94 SF/Year,,"8,000",,"10,000",
10,http://www.loopnet.com/Listing/19963876/143-Or...,143 Orchard St,"New York, NY",NY,10002,$180 SF/Year,Other Retail,800,,"6,472",
11,http://www.loopnet.com/Listing/18922237/142-14...,142-144 west 26 street,"New York, NY",NY,10001,$85 SF/Year,,"4,000",,"53,054",
12,http://www.loopnet.com/Listing/19814141/382-La...,382 Lafayette Street,"New York, NY",NY,10003,$218.18 SF/Year,,"2,200",,"13,000",
13,http://www.loopnet.com/Listing/19857624/155-We...,155 West 18th Street,"New York, NY",NY,10011,Rate,,"2,440 - 7,406",3,"7,406",
14,http://www.loopnet.com/Listing/20056601/155-Ch...,155 Chambers St,"New York, NY",NY,10007,$216 SF/Year,,750,,"8,900",
15,http://www.loopnet.com/Listing/20056597/70-74-...,70-74 Lafayette St,"New York, NY",NY,11209,$58.50 SF/Year,,"4,000",,"16,900",
16,http://www.loopnet.com/Listing/20054534/735-Ni...,735 Ninth Ave,"New York, NY",NY,10019,Rate,,"2,000",,"2,700",
17,http://www.loopnet.com/Listing/20051678/274-Gr...,274 Grand St,"New York, NY",NY,10002,Rate,,"1,514 - 3,664",2,"5,944",
18,http://www.loopnet.com/Listing/20051336/580-59...,580-590 W 161st St,"New York, NY",NY,10032,Rate,,"1,850",,"46,309",
19,http://www.loopnet.com/Listing/20050911/1143-1...,1143 1ST Ave,"New York, NY",NY,10065,$187.20 SF/Year,,"1,250",,"16,250",
20,http://www.loopnet.com/Listing/19621797/134-We...,134 West 37th Street,"New York, NY",NY,10018,$45-$79.20 SF/Year,Office Bldg,"2,500 - 10,000",2,"120,000",Extremely desirable office space in the heart ...
21,http://www.loopnet.com/Listing/19852777/517-Co...,517 Columbus Avenue,"New York, NY",NY,10024,$204.60 SF/Year,Restaurant,"2,346",,"2,345",This is the former Jackson Hole space has not ...
22,http://www.loopnet.com/Listing/19584842/76-Woo...,76 Wooster St,"New York, NY",NY,10012,$80-$84 SF/Year,,"3,000 - 5,000",2,"10,000",
23,http://www.loopnet.com/Listing/19632482/117-Ea...,117 East 15th Street,"New York, NY",NY,10003,$110.67-$120 SF/Year,,"3,300 - 6,600",3,"6,600",
24,http://www.loopnet.com/Listing/19872387/250-Hu...,250 Hudson St,"New York, NY",NY,10013,$75-$90 SF/Year,Office Bldg,"3,100 - 15,832",3,"394,424",
25,http://www.loopnet.com/Listing/19872550/485-Ma...,485 Madison Ave,"New York, NY",NY,10022,$54-$550 SF/Year,Office Bldg,"654 - 31,472",3,"302,000",
26,http://www.loopnet.com/Listing/18803035/315-Ma...,315 Madison Ave,"New York, NY",NY,10017,$60-$355 SF/Year,Office Bldg,"1,802 - 3,894",4,"148,370",
27,http://www.loopnet.com/Listing/19872441/315-Hu...,315 Hudson St,"New York, NY",NY,10013,$100-$175 SF/Year,Office Bldg,"3,922 - 5,881",5,"485,577",
28,http://www.loopnet.com/Listing/20002133/261-Fi...,261 Fifth Ave,"New York, NY",NY,10001,Rate,,"1,590 - 21,457",3,"444,716",
29,http://www.loopnet.com/Listing/19271844/100-Br...,100 Broad St,"New York, NY",NY,10004,$94 SF/Year,,"8,000",,"10,000",
...,...,...,...,...,...,...,...,...,...,...,...
1208,,,,,,,,,,,
1209,,,,,,,,,,,
1210,,,,,,,,,,,
1211,,,,,,,,,,,
1212,,,,,,,,,,,
1213,,,,,,,,,,,
1214,,,,,,,,,,,
1215,,,,,,,,,,,
1216,,,,,,,,,,,
1217,,,,,,,,,,,
1218,,,,,,,,,,,
1219,,,,,,,,,,,
1220,,,,,,,,,,,
1221,,,,,,,,,,,
1222,,,,,,,,,,,
1223,,,,,,,,,,,
1224,,,,,,,,,,,
1225,,,,,,,,,,,
1226,,,,,,,,,,,
1227,,,,,,,,,,,
1228,,,,,,,,,,,
1229,,,,,,,,,,,
1230,,,,,,,,,,,
1231,,,,,,,,,,,
1232,,,,,,,,,,,
1233,,,,,,,,,,,
1234,,,,,,,,,,,
1235,,,,,,,,,,,
1236,,,,,,,,,,,
1237,,,,,,,,,,,

### Editing address for geocoder

In [194]:
df['Full_street_address'] = df['Street_address'] + ', ' + df['State'] + ' ' + df['Postcode']
df.head()

,Web_address,Street_address,Locality,State,Postcode,Price,Property_type,SF_avail,Spaces_avail,Bldg_SF,Prop_desc,Full_street_address
0,http://www.loopnet.com/Listing/19621797/134-We...,134 West 37th Street,"New York, NY",NY,10018,$45-$79.20 SF/Year,Office Bldg,"2,500 - 10,000",2,"120,000",Extremely desirable office space in the heart ...,"134 West 37th Street, NY 10018"
1,http://www.loopnet.com/Listing/19852777/517-Co...,517 Columbus Avenue,"New York, NY",NY,10024,$204.60 SF/Year,Restaurant,"2,346",,"2,345",This is the former Jackson Hole space has not ...,"517 Columbus Avenue, NY 10024"
2,http://www.loopnet.com/Listing/19584842/76-Woo...,76 Wooster St,"New York, NY",NY,10012,$80-$84 SF/Year,,"3,000 - 5,000",2,"10,000",,"76 Wooster St, NY 10012"
3,http://www.loopnet.com/Listing/19632482/117-Ea...,117 East 15th Street,"New York, NY",NY,10003,$110.67-$120 SF/Year,,"3,300 - 6,600",3,"6,600",,"117 East 15th Street, NY 10003"
4,http://www.loopnet.com/Listing/19872387/250-Hu...,250 Hudson St,"New York, NY",NY,10013,$75-$90 SF/Year,Office Bldg,"3,100 - 15,832",3,"394,424",,"250 Hudson St, NY 10013"

In [195]:
import geocoder
geocoder.google(df.loc[0, 'Full_street_address']).latlng[0]

#(37.3860517, -122.0838511)

40.7523647

In [196]:
import numpy as np

lat = []
lon = []
for i in df['Full_street_address']:
    
    try:
        latlon = geocoder.google(i)
        lat.append(latlon.latlng[0])
        lon.append(latlon.latlng[1])
    
    except:
        lat.append(np.nan)
        lon.append(np.nan)
    
df['Latitude'] = lat
df['Longitude'] = lon
df.head()

In [197]:
df['Latitude'] = lat
df['Longitude'] = lon
df.head()

,Web_address,Street_address,Locality,State,Postcode,Price,Property_type,SF_avail,Spaces_avail,Bldg_SF,Prop_desc,Full_street_address,Latitude,Longitude
0,http://www.loopnet.com/Listing/19621797/134-We...,134 West 37th Street,"New York, NY",NY,10018,$45-$79.20 SF/Year,Office Bldg,"2,500 - 10,000",2,"120,000",Extremely desirable office space in the heart ...,"134 West 37th Street, NY 10018",40.752365,-73.988503
1,http://www.loopnet.com/Listing/19852777/517-Co...,517 Columbus Avenue,"New York, NY",NY,10024,$204.60 SF/Year,Restaurant,"2,346",,"2,345",This is the former Jackson Hole space has not ...,"517 Columbus Avenue, NY 10024",40.785576,-73.972575
2,http://www.loopnet.com/Listing/19584842/76-Woo...,76 Wooster St,"New York, NY",NY,10012,$80-$84 SF/Year,,"3,000 - 5,000",2,"10,000",,"76 Wooster St, NY 10012",40.723562,-74.001324
3,http://www.loopnet.com/Listing/19632482/117-Ea...,117 East 15th Street,"New York, NY",NY,10003,$110.67-$120 SF/Year,,"3,300 - 6,600",3,"6,600",,"117 East 15th Street, NY 10003",40.734987,-73.988662
4,http://www.loopnet.com/Listing/19872387/250-Hu...,250 Hudson St,"New York, NY",NY,10013,$75-$90 SF/Year,Office Bldg,"3,100 - 15,832",3,"394,424",,"250 Hudson St, NY 10013",40.724847,-74.007311

In [198]:
df.loc[:, 'Price'] = df['Price'].apply(lambda x: np.nan if "Rate" in x else x)
df['Price']

0         $45-$79.20 SF/Year
1            $204.60 SF/Year
2            $80-$84 SF/Year
3       $110.67-$120 SF/Year
4            $75-$90 SF/Year
5           $54-$550 SF/Year
6           $60-$355 SF/Year
7          $100-$175 SF/Year
8                        NaN
9                $94 SF/Year
10              $180 SF/Year
11               $85 SF/Year
12           $218.18 SF/Year
13                       NaN
14              $216 SF/Year
15            $58.50 SF/Year
16                       NaN
17                       NaN
18                       NaN
19           $187.20 SF/Year
20        $45-$79.20 SF/Year
21           $204.60 SF/Year
22           $80-$84 SF/Year
23      $110.67-$120 SF/Year
24           $75-$90 SF/Year
25          $54-$550 SF/Year
26          $60-$355 SF/Year
27         $100-$175 SF/Year
28                       NaN
29               $94 SF/Year
                ...
1208
1209
1210
1211
1212
1213
1214
1215
1216
1217
1218
1219
1220
1221
1222
1223
1224
1225
1226
1227
1228
1229
1230
1231
1232
1233
1234
1235
1236
1237
Name: Price, dtype: object

In [199]:
df1 = df.drop_duplicates()

In [200]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 42 entries, 0 to 892
Data columns (total 14 columns):
Web_address            42 non-null object
Street_address         42 non-null object
Locality               42 non-null object
State                  42 non-null object
Postcode               42 non-null object
Price                  33 non-null object
Property_type          42 non-null object
SF_avail               42 non-null object
Spaces_avail           42 non-null object
Bldg_SF                42 non-null object
Prop_desc              42 non-null object
Full_street_address    42 non-null object
Latitude               20 non-null float64
Longitude              20 non-null float64
dtypes: float64(2), object(12)
memory usage: 4.9+ KB

In [201]:
df['Price'].describe()

count     1098
unique      17
top
freq       600
Name: Price, dtype: object

## Scraping from another website using Selenium and PhantomJS

In [153]:
from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import time

In [269]:
pause = 5

driver = webdriver.PhantomJS(executable_path='/Users/peidacai/Downloads/phantomjs-2.1.1-macosx/bin/phantomjs')
dcap = dict(DesiredCapabilities.PHANTOMJS)
dcap['phantomjs.page.settings.userAgent'] = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36")

driver = webdriver.PhantomJS(executable_path='/Users/peidacai/Downloads/phantomjs-2.1.1-macosx/bin/phantomjs', \
                             desired_capabilities = dcap, service_args = ['--ignore-ssl-errors=true'])

driver.implicitly_wait(20)
driver.set_window_size(1024, 768) 
driver.get('http://www.cityfeet.com/cont/new-york-retail-space#')

lastHeight = driver.execute_script("return document.body.scrollHeight")
while True:
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(pause)
    newHeight = driver.execute_script("return document.body.scrollHeight")
    if newHeight == lastHeight:
        break
    lastHeight = newHeight

In [270]:
soup = BeautifulSoup(driver.page_source, "html.parser")

results = soup.find_all('div','property clearfix src-CF level-30')

cityfeet_results =[]
for d in results:
    cityfeet_results.append(d)

In [271]:
len(cityfeet_results)

12

In [272]:
results = soup.find_all('div','property clearfix src-LN level-20')

for d in results:
    cityfeet_results.append(d)

In [273]:
len(cityfeet_results)

1774

In [274]:
results = soup.find_all('div','property clearfix src-LN level-10')

for d in results:
    cityfeet_results.append(d)

In [275]:
len(cityfeet_results)

1774

In [276]:
results = soup.find_all('div','property clearfix src-LN level-40')

for d in results:
    cityfeet_results.append(d)

In [277]:
len(cityfeet_results)

1777

In [172]:
print cityfeet_results[256]

<div class="property clearfix src-LN level-40" data-listing-id="LN19852777">
<a class="listing" data-gaelabel="LN level-40" data-lid="LN19852777" href="/cont/ForLease/LN19852777/517-Columbus-Avenue-New-York-NY-10024">
<div class="photo-wrapper">
<div class="photo-stretchy-wrapper">
<!-- http://s.lnimg.com/photo/thumb_480/da6b8860315b4dc8889030441608ae84.jpg -->
<div class="photo-container" style="background-image: url(http://s.lnimg.com/photo/thumb_480/da6b8860315b4dc8889030441608ae84.jpg); filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://s.lnimg.com/photo/thumb_480/da6b8860315b4dc8889030441608ae84.jpg', sizingMethod='scale');">
<div class="media-shadow"></div>
<div class="photo-count">
<span><i class="icon-camera icon-white"></i> 10 photos</span>
</div>
</div>
</div>
</div>
</a>
<div class="description">
<div class="contentLeft">
<div class="description-left">
<div class="row-fluid">
<div class="span9">
<h2><a class="listing" data-lid="LN19852777" href="/cont/ForLease/LN19852777/517-Columbus-Avenue-New-York-NY-10024" title="517 Columbus Avenue">517 Columbus Avenue</a></h2>
</div>
</div>
<address>
<div>New York, NY 10024    </div>
</address>
<p class="propertyTypes"><span>Retail</span></p>
</div>
<div class="description-right">
<p class="stats"><strong class="price">$204.60 /sf/year</strong><strong>2,346 SF</strong></p>
</div>
<div class="propertydescription"><p>This is the former Jackson Hole space has not being on the market for over 40 years, With high ceilings, French doors to a sidewalk cafe and over 80ft of frontage its one of the the most visible corners on the UWS. The Restaurant is Vented ( 2 ) and NO KEY MONEY!!</p></div>
</div>
</div>
</div>

In [183]:
def get_cityfeet_details(listing_placard):
    
    listing = []
    
    # listing streetaddress
    try:
        listing.append(re.findall('title="(.+)">', str(listing_placard))[0])
    except:
        listing.append('')
         
    # listing state
    try:
        listing.append((re.findall('<address>\n<div>(.+)</div>', str(listing_placard))[0]).strip())
    except:
        listing.append('')
    
    # listing price
    try:
        listing.append(re.findall('"price">(.+)</strong><strong>', str(listing_placard))[0])
    except:
        listing.append('')
        
    # listing square feet available
    try:
        listing.append(re.findall('<strong>(.+)</strong>', str(listing_placard))[0])
    except:
        listing.append('')
        
    #listing property description
    try:
        listing.append(re.findall('"propertydescription"><p>((.|\n|\r)*)</p>', str(listing_placard))[0])
    except:
        listing.append('')
    
    return listing

In [278]:
cityfeet_list = []

for i in cityfeet_results:
    cityfeet_list.append(get_cityfeet_details(i))

dfc = pd.DataFrame(cityfeet_list, columns = ['Street_address', 'State', 'Price', 'SF_avail', 'Prop_desc'])

In [279]:
dfc.head()

,Street_address,State,Price,SF_avail,Prop_desc
0,327 Guy Lombardo Avenue,"Freeport, NY 11520",Rent Upon Req.,Size Upon Req.,(Busy Intersection on corner of Guy Lombardo a...
1,327 W 57th St. PRIME RESTAURANT-RETAIL FOR LEASE,"New York, NY 10019",$118.75 /sf/year,"3,840 SF",(Amazing Location! Perfect for Restaurant or R...
2,118 West 14th Street Retail,"New York, NY 10011",$140.00 /sf/year,"4,200 SF",(Prime retail at the base of a luxury resident...
3,"Prime Retail, 5th Avenue Ladies Mile","New York, NY 10011",Rent Upon Req.,"2,500 SF",(This impeccably maintained boutique cast iron...
4,BELOW MARKET!! PRIME MEATPACKING 14th ST,"New York, NY 10014",$65.00 /sf/year,"3,100 SF",(Boutique building located in the heart of the...

In [387]:
df_c = dfc[dfc['Price']!="Rent Upon Req."]

In [388]:
df_c.shape

(1134, 5)

In [389]:
df_c[df_c['Price'].str.contains("/sf/year")].shape

(1134, 5)

In [390]:
def get_zips(x):
    return re.findall('\d{5}', x)[0]

In [391]:
df_c.loc[:,'Postcode'] = df_c['State'].apply(get_zips)

In [392]:
df_c.head()

,Street_address,State,Price,SF_avail,Prop_desc,Postcode
1,327 W 57th St. PRIME RESTAURANT-RETAIL FOR LEASE,"New York, NY 10019",$118.75 /sf/year,"3,840 SF",(Amazing Location! Perfect for Restaurant or R...,10019
2,118 West 14th Street Retail,"New York, NY 10011",$140.00 /sf/year,"4,200 SF",(Prime retail at the base of a luxury resident...,10011
4,BELOW MARKET!! PRIME MEATPACKING 14th ST,"New York, NY 10014",$65.00 /sf/year,"3,100 SF",(Boutique building located in the heart of the...,10014
10,778 Nostrand Ave,"Brooklyn, NY 11215",$39.54 /sf/year,"1,669 SF",(Prime Retail Space located on the main strip ...,11215
14,5 Court Square,"Long Island City, NY 11101",$35.00 /sf/year,"3,500 SF","(Immediate possession, 2 5 year lease term,...",11101

In [393]:
def get_proper_add(x):
    
    proper_add = ['street', 'avenue', 'st', 'st.', 'ave', 'ave.', 'broadway', 'place', 'pl.', 'pl',\
                 'square', 'cresent', 'road', 'highway', 'turnpike', 'boulevard', 'steinway', '9', 'bypass', 'court', \
                 'parkway', 'lane', 'drive', 'americas', 'bowery', 'plaza']
    
    x = x.lower()
    x = x.split()
    
    
    if (x[-1] in proper_add) or (re.match('\d+', x[-1])):
        return False
    else:
        return True

In [394]:
df_c['Address_to_correct'] = df_c['Street_address'].apply(get_proper_add)

/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [395]:
df_d = df_c[df_c['Address_to_correct'] == True]
df_d.shape

(26, 7)

In [396]:
df_d

,Street_address,State,Price,SF_avail,Prop_desc,Postcode,Address_to_correct
1,327 W 57th St. PRIME RESTAURANT-RETAIL FOR LEASE,"New York, NY 10019",$118.75 /sf/year,"3,840 SF",(Amazing Location! Perfect for Restaurant or R...,10019,True
2,118 West 14th Street Retail,"New York, NY 10011",$140.00 /sf/year,"4,200 SF",(Prime retail at the base of a luxury resident...,10011,True
26,17 Knolls Crescent,"Bronx, NY 10463",$53.04 /sf/year,905 SF,"(Strip Mall, l)",10463,True
181,4205 Avenue D,"Brooklyn, NY 11203",$39.00 /sf/year,"1,700 - 3,400 SF",(Coldwell Banker Reliable Commercial Division ...,11203,True
375,2913 Avenue W,"Brooklyn, NY 11229",$33.00 /sf/year,"2,200 SF",(This is a brand new development in the vibran...,11229,True
427,1314 Avenue U,"Brooklyn, NY 11229",$49.00 /sf/year,"1,200 SF",(Prime retail strip Avenue U &amp; east 15 str...,11229,True
548,585 Veterans Road W,"Staten Island, NY 10309",$40.00 /sf/year,"1,000 - 2,400 SF",(Strip center with Pep Boys and Dunkin as co-t...,10309,True
593,95 Avenue B,"New York, NY 10009",$89.61 /sf/year,"1,540 SF","(In the east village, ground level, new buildi...",10009,True
657,25 Gardenville Parkway W,"Buffalo, NY 14224",$8.00 /sf/year,"3,532 SF",(Plaza was recently remodeled. Dollar General...,14224,True
834,1224 Avenue J,"Brooklyn, NY 11230",$90.00 /sf/year,"3,300 SF","(Fully renovated prime retail corner, r)",11230,True
848,33 Chestnut,"Cold Spring, NY 10516",$36.00 /sf/year,"2,000 SF",(SELLER FINANCING NOW Available!! Great Opport...,10516,True
915,1025 Little East Neck Road N,"West Babylon, NY 11704",$20.00 /sf/year,"1,000 - 3,500 SF","(New 4 unit Retail Space \nunit 1- 636 sq ft, ...",11704,True
1006,2855 Veterans Road W,"Staten Island, NY 10309",$55.00 /sf/year,"2,200 - 8,544 SF",(AAA RETAIL CORNER OPPOSITE 2 BUSY SHOPPING CE...,10309,True
1030,237 Vestal Parkway E,"Vestal, NY 13850",$8.00 /sf/year,"10,000 - 12,240 SF",,13850,True
1044,485 Schutt Road Extension,"Middletown, NY 10940",$15.00 /sf/year,"2,500 SF","(Office/retail space available for lease. 2,50...",10940,True
1059,130 7th Avenue S,"New York, NY 10014",$225.00 /sf/year,"2,000 SF",(Reference CoStar Property ID 1377306 for prio...,10014,True
1066,421 447 Avenue P,"Brooklyn, NY 11223",$50.00 /sf/year,720 SF,"(Ground floor retail (7,760 sq ft) and 33 apar...",11223,True
1087,2103 Grand Concourse,"Bronx, NY 10453",$78.22 /sf/year,675 SF,(Location Corner: SWProperty Description: Mult...,10453,True
1243,230 Oriskany Boulevard Yorkville,"Yorkville, NY 13495",$9.00 - $12.00 /sf/year,"400 - 3,500 SF","(Plaza retail row, w)",13495,True
1336,1395 Madison Avenue approximate,"Manhattan, NY 10029",$124.29 /sf/year,700 SF,"($8,000 per month | 700 SF John | \n Retail &...",10029,True
1356,505 Schutt Road Extension,"Middletown, NY 10940",$16.00 /sf/year,"3,500 SF",(NEWLY DEMISED VERY VISBLE END-CAP Available i...,10940,True
1357,505 Schutt Road Extension,"Middletown, NY 10940",$18.00 /sf/year,"1,500 SF",(Wallkill Town Center - Price Chopper Anchored...,10940,True
1462,3179 Erie Boulevard E,"Syracuse, NY 13214",$17.00 /sf/year,"1,745 SF","(Last 1,745 SF retail space is available for l...",13214,True
1519,1211 Avenue J,"Brooklyn, NY 11230",$60.00 /sf/year,"2,000 SF",(20 x 100\n2000 sq feet on Major Brooklyn Shop...,11230,True
1670,405 Central Park W,"New York, NY 10025",$116.40 /sf/year,750 SF,(6-Story Walk Up Building. Located on Central ...,10025,True
1765,328 Canal Address,"New York, NY 10013",$80.00 /sf/year,"5,000 SF",(Ceiling height 14 ft. \n\n2500 SQFT 1st Fl. +...,10013,True

In [397]:
# Correcting individually

df_c.loc[1, 'Street_address'] = '327 W 57th St'
df_c.loc[2, 'Street_address'] = '118 West 14th Street'
df_c.loc[214, 'Street_address'] = '26 W 14th Street'
df_c.loc[1336, 'Street_address'] = '1395 Madison Avenue'
df_c.loc[1765, 'Street_address'] = '328 Canal Street'
df_c.loc[1356, 'Street_address'] = '505 Schutt Road'
df_c.loc[1357, 'Street_address'] = '505 Schutt Road'
df_c.loc[1044, 'Street_address'] = '485 Schutt Road'

/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [398]:
df_c.head()

,Street_address,State,Price,SF_avail,Prop_desc,Postcode,Address_to_correct
1,327 W 57th St,"New York, NY 10019",$118.75 /sf/year,"3,840 SF",(Amazing Location! Perfect for Restaurant or R...,10019,True
2,118 West 14th Street,"New York, NY 10011",$140.00 /sf/year,"4,200 SF",(Prime retail at the base of a luxury resident...,10011,True
4,BELOW MARKET!! PRIME MEATPACKING 14th ST,"New York, NY 10014",$65.00 /sf/year,"3,100 SF",(Boutique building located in the heart of the...,10014,False
10,778 Nostrand Ave,"Brooklyn, NY 11215",$39.54 /sf/year,"1,669 SF",(Prime Retail Space located on the main strip ...,11215,False
14,5 Court Square,"Long Island City, NY 11101",$35.00 /sf/year,"3,500 SF","(Immediate possession, 2 5 year lease term,...",11101,False

In [401]:
df_c.shape

(1135, 7)

In [402]:
df_c[df_c['Price'].str.contains('/sf/year')].shape

ValueError: cannot index with vector containing NA / NaN values

In [403]:
def get_price(x):
    try:
        return re.findall('\d+\.\d\d', x)[0]
    except:
        return np.nan

In [404]:
df_c['Price_per_sf_per_year'] = df_c['Price'].apply(get_price)

In [406]:
df_c[df_c['Price_per_sf_per_year'].isnull()]

,Street_address,State,Price,SF_avail,Prop_desc,Postcode,Address_to_correct,Price_per_sf_per_year
214,26 W 14th Street,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [317]:
df_c.head()

,Street_address,State,Price,SF_avail,Prop_desc,Postcode,Address_to_correct,Price_per_sf_per_year
1,327 W 57th St,"New York, NY 10019",$118.75 /sf/year,"3,840 SF",(Amazing Location! Perfect for Restaurant or R...,10019,True,118.75
2,118 West 14th Street,"New York, NY 10011",$140.00 /sf/year,"4,200 SF",(Prime retail at the base of a luxury resident...,10011,True,140.00
4,BELOW MARKET!! PRIME MEATPACKING 14th ST,"New York, NY 10014",$65.00 /sf/year,"3,100 SF",(Boutique building located in the heart of the...,10014,False,65.00
10,778 Nostrand Ave,"Brooklyn, NY 11215",$39.54 /sf/year,"1,669 SF",(Prime Retail Space located on the main strip ...,11215,False,39.54
14,5 Court Square,"Long Island City, NY 11101",$35.00 /sf/year,"3,500 SF","(Immediate possession, 2 5 year lease term,...",11101,False,35.00

In [407]:
df_c.drop(4, axis = 0, inplace = True)
df_c.drop(214, axis = 0, inplace = True)
df_c.head()

,Street_address,State,Price,SF_avail,Prop_desc,Postcode,Address_to_correct,Price_per_sf_per_year
1,327 W 57th St,"New York, NY 10019",$118.75 /sf/year,"3,840 SF",(Amazing Location! Perfect for Restaurant or R...,10019,True,118.75
2,118 West 14th Street,"New York, NY 10011",$140.00 /sf/year,"4,200 SF",(Prime retail at the base of a luxury resident...,10011,True,140.00
10,778 Nostrand Ave,"Brooklyn, NY 11215",$39.54 /sf/year,"1,669 SF",(Prime Retail Space located on the main strip ...,11215,False,39.54
14,5 Court Square,"Long Island City, NY 11101",$35.00 /sf/year,"3,500 SF","(Immediate possession, 2 5 year lease term,...",11101,False,35.00
23,16 W 8th Street,"New York, NY 10011",$149.61 /sf/year,"1,163 SF",(Excellent space steps from Washington Square ...,10011,False,149.61

In [408]:
df_c[df_c['Price_per_sf_per_year'].isnull()]

Empty DataFrame
Columns: [Street_address, State, Price, SF_avail, Prop_desc, Postcode, Address_to_correct, Price_per_sf_per_year]
Index: []

In [409]:
df_c.loc[:,'City'] = df_c["State"].apply(lambda x: (str(x)).split(',')[0])
df_c.head(20)

,Street_address,State,Price,SF_avail,Prop_desc,Postcode,Address_to_correct,Price_per_sf_per_year,City
1,327 W 57th St,"New York, NY 10019",$118.75 /sf/year,"3,840 SF",(Amazing Location! Perfect for Restaurant or R...,10019,True,118.75,New York
2,118 West 14th Street,"New York, NY 10011",$140.00 /sf/year,"4,200 SF",(Prime retail at the base of a luxury resident...,10011,True,140.00,New York
10,778 Nostrand Ave,"Brooklyn, NY 11215",$39.54 /sf/year,"1,669 SF",(Prime Retail Space located on the main strip ...,11215,False,39.54,Brooklyn
14,5 Court Square,"Long Island City, NY 11101",$35.00 /sf/year,"3,500 SF","(Immediate possession, 2 5 year lease term,...",11101,False,35.00,Long Island City
23,16 W 8th Street,"New York, NY 10011",$149.61 /sf/year,"1,163 SF",(Excellent space steps from Washington Square ...,10011,False,149.61,New York
24,3821 Broadway,"New York, NY 10032",$140.00 - $140.24 /sf/year,830 - 966 SF,(Great corner location in a busy area of Washi...,10032,False,140.00,New York
26,17 Knolls Crescent,"Bronx, NY 10463",$53.04 /sf/year,905 SF,"(Strip Mall, l)",10463,True,53.04,Bronx
27,256 W 109th Street,"New York, NY 10025",$205.26 /sf/year,380 SF,"(one story street retail, l)",10025,False,205.26,New York
28,270 E 10th Street,"New York, NY 10009",$65.16 /sf/year,"1,200 SF","(Ready to operate,Please do not talk to any em...",10009,False,65.16,New York
30,120 Christopher Street,"New York, NY 10014",$129.00 /sf/year,"1,200 SF",(1200 sf basement 400 sf 30 seats Vietnam...,10014,False,129.00,New York
31,15 W 8th Street,"New York, NY 10011",$95.01 /sf/year,"2,000 SF",(Great location in west village close to fifth...,10011,False,95.01,New York
32,97 1st Avenue,"New York, NY 10003",$81.58 /sf/year,"2,500 SF","(Beautiful corner restaurant 2,500 ground fl...",10003,False,81.58,New York
33,203 Chrystie Street,"New York, NY 10002",$112.50 - $120.00 /sf/year,"700 - 1,600 SF",(1600 sf space divisible or taken as is locate...,10002,False,112.50,New York
34,114 Stanton Street,"New York, NY 10002",$138.46 /sf/year,"1,300 SF",(114 Stanton street one of the most incredible...,10002,False,138.46,New York
35,22 E Merrick Road,"Freeport, NY 11520",$14.00 /sf/year,"6,400 SF",(To Watch a Video of this property please go t...,11520,False,14.00,Freeport
36,964 Middle Country Road,"Saint James, NY 11780",$24.00 /sf/year,"3,700 SF",(: Multi level building for lease located at ...,11780,False,24.00,Saint James
37,294 Waverly Avenue,"Patchogue, NY 11772",$17.14 /sf/year,"1,400 SF",(Retail/Office building for sale or lease loca...,11772,False,17.14,Patchogue
38,4760 Sunrise Highway,"Bohemia, NY 11716",$20.00 /sf/year,"3,200 - 14,050 SF",(Prime location at the corner of Sunrise Highw...,11716,False,20.00,Bohemia
39,92 E Suffolk Avenue,"Central Islip, NY 11722",$16.00 /sf/year,"1,800 SF","(Includes bar, boarding house and rental room ...",11722,False,16.00,Central Islip
40,1815 E Jericho Turnpike,"Huntington, NY 11743",$24.00 /sf/year,"9,000 SF",(Retail space available on heavily traveled Je...,11743,False,24.00,Huntington

### New York City Zipcodes

In [331]:
manhattan_zip = pd.read_csv('manhattan_zip.txt', sep='\n')

In [333]:
brooklyn_zip = pd.read_csv('brooklyn_zip.txt', sep = '\n')

In [334]:
bronx_zip = pd.read_csv('bronx.txt', sep = '\n')

In [335]:
queens_zip = pd.read_csv('queens.txt', sep = '\n')

In [336]:
statten_zip = pd.read_csv('statten.txt', sep ='\n')

In [364]:
statten_zip = statten_zip.T.values.tolist()[0]

In [366]:
manhattan_zip = manhattan_zip.T.values.tolist()[0]

In [367]:
bronx_zip = bronx_zip.T.values.tolist()[0]
queens_zip = queens_zip.T.values.tolist()[0]
brooklyn_zip = brooklyn_zip.T.values.tolist()[0]

In [380]:
nyc_less_stat_zip = manhattan_zip + bronx_zip + brooklyn_zip + queens_zip

In [381]:
nyc_less_stat_zip = pd.Series(nyc_less_stat_zip)
nyc_less_stat_zip.to_csv('nyc_less_stat_zip.txt')

In [368]:
nyc_zip = manhattan_zip + bronx_zip + brooklyn_zip + queens_zip + statten_zip
nyc_zip

[10001,
 10002,
 10003,
 10004,
 10005,
 10006,
 10007,
 10009,
 10010,
 10011,
 10012,
 10013,
 10014,
 10016,
 10017,
 10018,
 10019,
 10020,
 10021,
 10022,
 10023,
 10024,
 10025,
 10026,
 10027,
 10028,
 10029,
 10030,
 10031,
 10032,
 10033,
 10034,
 10035,
 10036,
 10037,
 10038,
 10039,
 10040,
 10044,
 10048,
 10065,
 10069,
 10075,
 10111,
 10115,
 10128,
 10280,
 10281,
 10282,
 10451,
 10452,
 10453,
 10454,
 10455,
 10456,
 10457,
 10458,
 10459,
 10460,
 10461,
 10462,
 10465,
 10466,
 10467,
 10468,
 10469,
 10470,
 10471,
 10472,
 10473,
 10474,
 10475,
 11201,
 11203,
 11204,
 11205,
 11206,
 11207,
 11208,
 11209,
 11210,
 11211,
 11212,
 11213,
 11214,
 11215,
 11216,
 11217,
 11218,
 11219,
 11220,
 11221,
 11222,
 11223,
 11224,
 11225,
 11226,
 11228,
 11229,
 11230,
 11231,
 11232,
 11233,
 11234,
 11235,
 11236,
 11237,
 11238,
 11239,
 11251,
 11001,
 11004,
 11005,
 11040,
 11096,
 11101,
 11102,
 11103,
 11104,
 11105,
 11106,
 11109,
 11354,
 11355,
 11356,
 11357,
 11358,
 11359,
 11360,
 11361,
 11362,
 11363,
 11364,
 11365,
 11366,
 11367,
 11368,
 11369,
 11371,
 11372,
 11373,
 11374,
 11375,
 11377,
 11378,
 11379,
 11385,
 11411,
 11412,
 11413,
 11414,
 11415,
 11416,
 11417,
 11418,
 11419,
 11420,
 11421,
 11422,
 11423,
 11426,
 11427,
 11428,
 11429,
 11430,
 11432,
 11433,
 11434,
 11435,
 11436,
 11451,
 11691,
 11692,
 11694,
 11697,
 10301,
 10302,
 10303,
 10304,
 10305,
 10306,
 10307,
 10308,
 10309,
 10310,
 10312,
 10314]

In [370]:
nyc_zip = pd.Series(nyc_zip)
nyc_zip.to_csv('nyc_zip.txt')

### Removing rows without zip code

In [410]:
df_c[df_c['Postcode'].isnull()]

Empty DataFrame
Columns: [Street_address, State, Price, SF_avail, Prop_desc, Postcode, Address_to_correct, Price_per_sf_per_year, City]
Index: []

### Checking number of entries in nyc

In [411]:
df_c['Postcode'] = df_c['Postcode'].astype(int)

In [412]:
df_c[df_c['Postcode'].isin(nyc_zip)].shape

(569, 9)

#### Number of entries in Manhattan

In [413]:
df_c[df_c['Postcode'].isin(manhattan_zip)].shape

(180, 9)

#### Number of entries in NYC less Statten Island

In [414]:
df_c[df_c['Postcode'].isin(nyc_less_stat_zip)].shape

(554, 9)

## Cleaning up the dataframe

In [383]:
df_c.loc[:, 'SF_avail'] = df_c['SF_avail'].apply(lambda x : x.replace(' SF', ''))
df_c.head()

,Street_address,State,Price,SF_avail,Prop_desc,Postcode,Address_to_correct,Price_per_sf_per_year,City
1,327 W 57th St,"New York, NY 10019",$118.75 /sf/year,"3,840",(Amazing Location! Perfect for Restaurant or R...,10019,True,118.75,New York
2,118 West 14th Street,"New York, NY 10011",$140.00 /sf/year,"4,200",(Prime retail at the base of a luxury resident...,10011,True,140.00,New York
10,778 Nostrand Ave,"Brooklyn, NY 11215",$39.54 /sf/year,"1,669",(Prime Retail Space located on the main strip ...,11215,False,39.54,Brooklyn
14,5 Court Square,"Long Island City, NY 11101",$35.00 /sf/year,"3,500","(Immediate possession, 2 5 year lease term,...",11101,False,35.00,Long Island City
23,16 W 8th Street,"New York, NY 10011",$149.61 /sf/year,"1,163",(Excellent space steps from Washington Square ...,10011,False,149.61,New York

In [384]:
df_c.loc[:, 'SF_avail'] = df_c['SF_avail'].apply(lambda x : x.replace(',', ''))
df_c.head()

,Street_address,State,Price,SF_avail,Prop_desc,Postcode,Address_to_correct,Price_per_sf_per_year,City
1,327 W 57th St,"New York, NY 10019",$118.75 /sf/year,3840,(Amazing Location! Perfect for Restaurant or R...,10019,True,118.75,New York
2,118 West 14th Street,"New York, NY 10011",$140.00 /sf/year,4200,(Prime retail at the base of a luxury resident...,10011,True,140.00,New York
10,778 Nostrand Ave,"Brooklyn, NY 11215",$39.54 /sf/year,1669,(Prime Retail Space located on the main strip ...,11215,False,39.54,Brooklyn
14,5 Court Square,"Long Island City, NY 11101",$35.00 /sf/year,3500,"(Immediate possession, 2 5 year lease term,...",11101,False,35.00,Long Island City
23,16 W 8th Street,"New York, NY 10011",$149.61 /sf/year,1163,(Excellent space steps from Washington Square ...,10011,False,149.61,New York

### Cleaning up street address

In [386]:
df_c.loc[:, 'Street_address'] = df_c['Street_address'] + ', NY ' + str(df_c['Postcode'])
df_c.head()

,Street_address,State,Price,SF_avail,Prop_desc,Postcode,Address_to_correct,Price_per_sf_per_year,City
1,"327 W 57th St, NY 1 10019\n2 10011...","New York, NY 10019",$118.75 /sf/year,3840,(Amazing Location! Perfect for Restaurant or R...,10019,True,118.75,New York
2,"118 West 14th Street, NY 1 10019\n2 ...","New York, NY 10011",$140.00 /sf/year,4200,(Prime retail at the base of a luxury resident...,10011,True,140.00,New York
10,"778 Nostrand Ave, NY 1 10019\n2 10...","Brooklyn, NY 11215",$39.54 /sf/year,1669,(Prime Retail Space located on the main strip ...,11215,False,39.54,Brooklyn
14,"5 Court Square, NY 1 10019\n2 1001...","Long Island City, NY 11101",$35.00 /sf/year,3500,"(Immediate possession, 2 5 year lease term,...",11101,False,35.00,Long Island City
23,"16 W 8th Street, NY 1 10019\n2 100...","New York, NY 10011",$149.61 /sf/year,1163,(Excellent space steps from Washington Square ...,10011,False,149.61,New York

In [240]:
df_cityfeet = pd.concat([df_c['Street_address'], df_c['SF_avail'], df_c['Price_per_sf_per_year'], df_c['Prop_desc']], axis = 1)
df_cityfeet.reset_index(inplace = True, drop = True)
df_cityfeet.head()

,Street_address,SF_avail,Price_per_sf_per_year,Prop_desc
0,"327 W 57th St, NY 10019",3840,118.75,(Amazing Location! Perfect for Restaurant or R...
1,"118 West 14th Street, NY 10011",4200,140.00,(Prime retail at the base of a luxury resident...
2,"155 Chambers Street, NY 10007",750,216.00,"($13,500/month\nSuper High Traffic Retail Stor..."
3,"321 Bleecker Street, NY 10014",600,370.00,"(Store fully renovated, turn key opportunity. ..."
4,"323 Bleecker Street, NY 10014",1420,295.77,"(All renovated, turn key retail opportunity wi..."

In [244]:
def clean_sf(x):
    if '-' in x:
        return int(x.split('-')[1])
    else:
        return int(x)

In [245]:
s = '1200 - 1500'
clean_sf(s)

1500

In [247]:
df_cityfeet.loc[:, 'SF_avail'] = df_cityfeet['SF_avail'].apply(clean_sf)

TypeError: argument of type 'int' is not iterable

In [251]:
df_cityfeet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 131 entries, 0 to 130
Data columns (total 4 columns):
Street_address           131 non-null object
SF_avail                 131 non-null int64
Price_per_sf_per_year    131 non-null float64
Prop_desc                131 non-null object
dtypes: float64(1), int64(1), object(2)
memory usage: 4.2+ KB

In [250]:
df_cityfeet.loc[:, 'Price_per_sf_per_year'] = df_cityfeet['Price_per_sf_per_year'].astype(float)

In [252]:
import numpy as np

lat = []
lon = []
for i in df_cityfeet['Street_address']:
    
    try:
        latlon = geocoder.google(i)
        lat.append(latlon.latlng[0])
        lon.append(latlon.latlng[1])
    
    except:
        lat.append(np.nan)
        lon.append(np.nan)
    
df_cityfeet['Latitude'] = lat
df_cityfeet['Longitude'] = lon
df_cityfeet.head()

,Street_address,SF_avail,Price_per_sf_per_year,Prop_desc,Latitude,Longitude
0,"327 W 57th St, NY 10019",3840,118.75,(Amazing Location! Perfect for Restaurant or R...,40.767498,-73.984111
1,"118 West 14th Street, NY 10011",4200,140.00,(Prime retail at the base of a luxury resident...,40.737629,-73.997937
2,"155 Chambers Street, NY 10007",750,216.00,"($13,500/month\nSuper High Traffic Retail Stor...",40.716076,-74.009971
3,"321 Bleecker Street, NY 10014",600,370.00,"(Store fully renovated, turn key opportunity. ...",40.733199,-74.003924
4,"323 Bleecker Street, NY 10014",1420,295.77,"(All renovated, turn key retail opportunity wi...",40.733286,-74.003929

In [254]:
df_cityfeet['Zipcode'] = list(df_c['Postcode'])
df_cityfeet.head()

,Street_address,SF_avail,Price_per_sf_per_year,Prop_desc,Latitude,Longitude,Zipcode
0,"327 W 57th St, NY 10019",3840,118.75,(Amazing Location! Perfect for Restaurant or R...,40.767498,-73.984111,10019
1,"118 West 14th Street, NY 10011",4200,140.00,(Prime retail at the base of a luxury resident...,40.737629,-73.997937,10011
2,"155 Chambers Street, NY 10007",750,216.00,"($13,500/month\nSuper High Traffic Retail Stor...",40.716076,-74.009971,10007
3,"321 Bleecker Street, NY 10014",600,370.00,"(Store fully renovated, turn key opportunity. ...",40.733199,-74.003924,10014
4,"323 Bleecker Street, NY 10014",1420,295.77,"(All renovated, turn key retail opportunity wi...",40.733286,-74.003929,10014

In [268]:
df_cityfeet[df_cityfeet['Street_address'].str.contains('256 W 109')]

Empty DataFrame
Columns: [Street_address, SF_avail, Price_per_sf_per_year, Prop_desc, Latitude, Longitude, Zipcode]
Index: []

In [256]:
df_cityfeet.loc[:,'Zipcode'] = df_cityfeet['Zipcode'].astype(int)

In [257]:
df_cityfeet.describe()

,SF_avail,Price_per_sf_per_year,Latitude,Longitude,Zipcode
count,131.000000,131.000000,131.000000,131.000000,131.000000
mean,8403.114504,134.322824,40.755279,-73.978563,10020.282443
std,48950.738279,98.794998,0.038811,0.024065,21.166110
min,279.000000,18.000000,40.703561,-74.012465,10001.000000
25%,800.000000,64.845000,40.724422,-74.000122,10010.000000
50%,1500.000000,105.000000,40.738547,-73.986773,10014.000000
75%,2694.000000,163.930000,40.785749,-73.953785,10028.500000
max,520000.000000,600.000000,40.862353,-73.925560,10128.000000

In [258]:
df_cityfeet[df_cityfeet['SF_avail'] > 50000]

,Street_address,SF_avail,Price_per_sf_per_year,Prop_desc,Latitude,Longitude,Zipcode
64,"2340 5th Avenue, NY 10037",520000,49.0,(Build to Suit Commercial Development in Harle...,40.816982,-73.934953,10037
67,"2005 2023 Third Avenue, NY 10029",121500,50.0,(Build to Suit Commercial Development in East ...,40.794119,-73.942374,10029
68,"315 E 94th Street, NY 10128",185000,60.0,(Build to Suit Commercial Development in the U...,40.782479,-73.946914,10128

In [259]:
df_cityfeet.to_csv('cityfeet_retail_rental.csv')

In [266]:
pd.pivot_table(df_cityfeet, values = ['SF_avail', 'Price_per_sf_per_year'], index = ['Zipcode'], aggfunc='count')

         Price_per_sf_per_year  SF_avail
Zipcode
10001                        1         1
10002                       15        15
10003                       10        10
10004                        1         1
10005                        1         1
10007                        3         3
10009                        2         2
10011                        8         8
10012                       11        11
10013                        8         8
10014                       10        10
10016                        1         1
10017                        2         2
10018                        3         3
10019                        1         1
10021                        3         3
10022                        5         5
10023                        1         1
10024                        4         4
10025                        2         2
10026                        1         1
10027                        3         3
10028                        2         2
10029                       10        10
10030                        1         1
10031                        2         2
10032                        3         3
10033                        4         4
10035                        2         2
10036                        2         2
10037                        1         1
10038                        1         1
10040                        1         1
10065                        2         2
10075                        1         1
10128                        3         3

In [267]:
pd.pivot_table(df_cityfeet, values = ['SF_avail', 'Price_per_sf_per_year'], index = ['Zipcode'])

         Price_per_sf_per_year       SF_avail
Zipcode
10001               165.000000    2700.000000
10002               104.502667    1413.333333
10003               144.753000    1600.000000
10004                43.200000    1250.000000
10005                25.000000    2750.000000
10007               142.833333    1587.666667
10009                74.805000    1434.000000
10011               133.121250    3304.750000
10012               259.555455    2113.636364
10013               167.873750    2676.750000
10014               217.896000    1132.800000
10016                57.000000    5200.000000
10017                95.440000    1383.000000
10018                56.990000    7450.000000
10019               118.750000    3840.000000
10021               144.356667    2400.000000
10022               104.798000    1932.600000
10023               150.000000     800.000000
10024               208.842500    1442.750000
10025               150.205000    1330.000000
10026                64.890000    1165.000000
10027                82.996667    2486.666667
10028               200.820000    1050.000000
10029                57.577000   13801.300000
10030                60.000000    1560.000000
10031                78.500000     850.000000
10032                65.110000     853.333333
10033                79.592500    1240.000000
10035                68.055000    4850.000000
10036               155.000000    2350.000000
10037                49.000000  520000.000000
10038                50.000000    6000.000000
10040                80.000000    6000.000000
10065               124.425000     950.000000
10075               430.110000     279.000000
10128                73.793333   66166.666667

In [173]:
df.head(1)

,Web_address,Street_address,Locality,State,Postcode,Price,Property_type,SF_avail,Spaces_avail,Bldg_SF,Prop_desc,Full_street_address,Latitude,Longitude
0,http://www.loopnet.com/Listing/19621797/134-We...,134 West 37th Street,"New York, NY",NY,10018,$45-$79.20 SF/Year,Office Bldg,"2,500 - 10,000",2,"120,000",Extremely desirable office space in the heart ...,"134 West 37th Street, NY 10018",40.752365,-73.988503

In [171]:
sample = cityfeet_results[0]
sp = BeautifulSoup(sample, "lxml")

b = soup.find_all('div','propertydescription')
print b

TypeError: 'NoneType' object is not callable

In [122]:
url = 'http://www.cityfeet.com/cont/ny/new-york-retail-space#'

"""58.176.46.248
4.31.142.200
64.20.45.138"""

proxies = {
    'http':'http://4.31.142.200'
    }

cityfeet_results = []

r = requests.get(url, proxies=proxies)
if str(r) == "<Response [200]>":

    page = r.content
    soup = BeautifulSoup(page, 'lxml')
    
    
    for d in soup.find_all(class_ = 'property clearfix src-CF level-30'):
        cityfeet_results.append(d)

In [123]:
len(cityfeet_results)

0

In [ ]:
for pg in range(2, max_pages+1, 1):

    url = url_template1 + str(pg) + url_template2

    r = requests.get(url, proxies=proxies)
    if str(r) == "<Response [200]>":

        page = r.content
        soup = BeautifulSoup(page, 'lxml')

        results.append(get_listings(soup))
        for i in results:
            page_list.append(get_listing_details(i))

    else:
        print "This url is not responding favorably."
        print "url =", url
        print "response =", r



s = BeautifulSoup(driver.page_source)
r = re.compile(r'jobdetail\.ftl\?job=\d+$')

for a in s.findAll('a', href=r):
    tr = a.findParent('tr')
    td = tr.findAll('td')

    job = {}
    job['title'] = a.text
    job['url'] = urlparse.urljoin(link, a['href'])
    job['location'] = td[2].text
    jobs.append(job)

next_page_elem = self.driver.find_element_by_id('next')
next_page_link = s.find('a', text='%d' % pageno)

if next_page_link:
    next_page_elem.click()
    pageno += 1
    sleep(1)
else:
    break

return jobs

## Get demographic website

## Resources and references

1. Source for property listings - http://www.loopnet.com/